"""Rsync-client onboarding: compose snippet + auto-provisioned API key.

Shared by the settings API (specs/settings-ui.md AC-008); the HTMX wizard in
app/routes/settings.py is retired in cycle S3.
"""

import re
import secrets
from dataclasses import dataclass
from datetime import date
from typing import Optional
from uuid import UUID

from fastapi import Request
from sqlmodel import Session, select

from app.api.deps import hash_api_key
from app.models.sync_log import ApiKey
from app.utils import utc_now

KEY_PREFIX = "rsv_"


def sanitize_source_name(name: str) -> str:
    """Kebab-case a source name for use in container and key names."""
    name = name.strip().lower()
    name = re.sub(r"[^a-z0-9]+", "-", name)
    return name.strip("-")


def parse_rsync_source(rsync_source: str) -> Optional[tuple[str, str, str]]:
    """Parse ``user@host:/path`` into (user, host, path); None if malformed."""
    match = re.match(r"^([^@]+)@([^:]+):(.+)$", rsync_source.strip())
    if not match:
        return None
    return match.group(1), match.group(2), match.group(3)


def detect_hub_url(request: Request) -> str:
    """Hub URL as seen by the client, honouring proxy headers uvicorn trusts."""
    proto = request.headers.get("X-Forwarded-Proto", request.url.scheme)
    host = request.headers.get(
        "X-Forwarded-Host", request.headers.get("host", "localhost:8000")
    )
    return f"{proto}://{host}"


def unique_key_name(session: Session, user_id: UUID, base_name: str) -> str:
    """Return ``base_name`` or ``base_name-N`` so active key names stay unique per user."""
    name = base_name
    suffix = 1
    while True:
        existing = session.exec(
            select(ApiKey).where(
                ApiKey.user_id == user_id,
                ApiKey.name == name,
                ApiKey.is_active.is_(True),  # type: ignore[attr-defined]
            )
        ).first()
        if not existing:
            return name
        suffix += 1
        name = f"{base_name}-{suffix}"


def generate_compose_snippet(
    *,
    source_name: str,
    remote_user: str,
    remote_host: str,
    remote_path: str,
    hub_url: str,
    api_key: str,
    cron_schedule: str,
    rsync_args: str,
    sync_mode: str,
    ssh_key_path: str,
) -> str:
    """Docker Compose YAML for one rsync-client container."""
    data_mount = "./data:/data:ro" if sync_mode == "push" else "./data:/data"
    return f"""\
# Rsync Client — {source_name}
# Generated by Rsync Log Viewer on {date.today().isoformat()}
# Add this to your docker-compose.yml

services:
  rsync-client-{source_name}:
    image: ghcr.io/finish06/rsync-client:latest
    container_name: rsync-{source_name}
    restart: unless-stopped
    environment:
      - REMOTE_HOST={remote_host}
      - REMOTE_USER={remote_user}
      - REMOTE_PATH={remote_path}
      - RSYNC_VIEWER_URL={hub_url}
      - RSYNC_VIEWER_API_KEY={api_key}
      - RSYNC_SOURCE_NAME={source_name}
      - CRON_SCHEDULE={cron_schedule}
      - RSYNC_ARGS={rsync_args}
      - SYNC_MODE={sync_mode}
    volumes:
      - {ssh_key_path}:/home/rsync/.ssh/id_rsa:ro
      - {data_mount}
"""


@dataclass
class ProvisionedClient:
    source_name: str
    key_name: str
    api_key: str
    snippet: str


def provision_client(
    session: Session,
    *,
    user_id: UUID,
    hub_url: str,
    source_name: str,
    rsync_source: str,
    cron_schedule: str,
    ssh_key_path: str,
    rsync_args: str,
    sync_mode: str,
) -> ProvisionedClient:
    """Create the API key and build the snippet. Raises ValueError on bad input."""
    parsed = parse_rsync_source(rsync_source)
    if parsed is None:
        raise ValueError("Invalid rsync source. Expected: user@host:/path")
    clean_name = sanitize_source_name(source_name)
    if not clean_name:
        raise ValueError("Source name must contain letters or digits")
    remote_user, remote_host, remote_path = parsed

    key_name = unique_key_name(session, user_id, f"rsync-client-{clean_name}")
    raw_key = KEY_PREFIX + secrets.token_urlsafe(32)
    session.add(
        ApiKey(
            key_hash=hash_api_key(raw_key),
            key_prefix=raw_key[:8],
            name=key_name,
            is_active=True,
            user_id=user_id,
            created_at=utc_now(),
        )
    )
    session.commit()

    snippet = generate_compose_snippet(
        source_name=clean_name,
        remote_user=remote_user,
        remote_host=remote_host,
        remote_path=remote_path,
        hub_url=hub_url,
        api_key=raw_key,
        cron_schedule=cron_schedule,
        rsync_args=rsync_args,
        sync_mode=sync_mode,
        ssh_key_path=ssh_key_path,
    )
    return ProvisionedClient(clean_name, key_name, raw_key, snippet)
