"""Migration drift tests — specs/security-hardening-v2.md AC-005.

Runs the Alembic chain against a fresh database (NOT the create_all()-built
test database) and asserts that autogenerate finds no pending operations.
"""

import os
from urllib.parse import urlsplit, urlunsplit

import pytest
import sqlalchemy as sa
from alembic import command
from alembic.config import Config
from alembic.util.exc import AutogenerateDiffsDetected

from app.config import get_settings

MIGRATION_DB_NAME = "rsync_viewer_migration_check"


def _server_url_and_db(test_url: str) -> tuple[str, str]:
    """Split a database URL into (URL pointing at the maintenance db, db name)."""
    parts = urlsplit(test_url)
    db_name = parts.path.lstrip("/")
    admin_url = urlunsplit(parts._replace(path="/postgres"))
    return admin_url, db_name


@pytest.fixture
def fresh_database_url():
    """Create an empty database for migration runs; drop it afterwards."""
    from tests.conftest import TEST_DATABASE_URL

    admin_url, _ = _server_url_and_db(TEST_DATABASE_URL)
    admin_engine = sa.create_engine(admin_url, isolation_level="AUTOCOMMIT")
    with admin_engine.connect() as conn:
        conn.execute(sa.text(f'DROP DATABASE IF EXISTS "{MIGRATION_DB_NAME}"'))
        conn.execute(sa.text(f'CREATE DATABASE "{MIGRATION_DB_NAME}"'))

    parts = urlsplit(TEST_DATABASE_URL)
    fresh_url = urlunsplit(parts._replace(path=f"/{MIGRATION_DB_NAME}"))

    previous = os.environ.get("DATABASE_URL")
    os.environ["DATABASE_URL"] = fresh_url
    get_settings.cache_clear()
    try:
        yield fresh_url
    finally:
        if previous is None:
            os.environ.pop("DATABASE_URL", None)
        else:
            os.environ["DATABASE_URL"] = previous
        get_settings.cache_clear()
        with admin_engine.connect() as conn:
            conn.execute(
                sa.text(f'DROP DATABASE IF EXISTS "{MIGRATION_DB_NAME}" WITH (FORCE)')
            )
        admin_engine.dispose()


def _alembic_config() -> Config:
    # Built without alembic.ini so env.py skips fileConfig(), which would
    # reconfigure logging and disable other tests' caplog captures.
    root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    cfg = Config()
    cfg.set_main_option("script_location", os.path.join(root, "alembic"))
    return cfg


class TestAC005MigrationDrift:
    def test_ac005_alembic_check_clean(self, fresh_database_url):
        """Upgrading to head must produce a schema identical to the models."""
        cfg = _alembic_config()
        command.upgrade(cfg, "head")
        try:
            command.check(cfg)
        except AutogenerateDiffsDetected as exc:
            pytest.fail(f"Model/migration drift detected: {exc}")

    def test_ac005_api_keys_active_prefix_index_created(self, fresh_database_url):
        """The composite index added in the perf work must come from a migration."""
        cfg = _alembic_config()
        command.upgrade(cfg, "head")
        engine = sa.create_engine(fresh_database_url)
        try:
            index_names = {
                idx["name"] for idx in sa.inspect(engine).get_indexes("api_keys")
            }
        finally:
            engine.dispose()
        assert "ix_api_keys_active_prefix" in index_names
