"""baseline schema

Revision ID: d911ea2048ad
Revises:
Create Date: 2026-03-01 20:29:08.968444

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # noqa: F401 — needed for sqlmodel.sql.sqltypes.AutoString
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "d911ea2048ad"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sync_logs",
        sa.Column(
            "source_name", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False
        ),
        sa.Column("start_time", sa.DateTime(), nullable=False),
        sa.Column("end_time", sa.DateTime(), nullable=False),
        sa.Column("raw_content", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("total_size_bytes", sa.BigInteger(), nullable=True),
        sa.Column("bytes_sent", sa.BigInteger(), nullable=True),
        sa.Column("bytes_received", sa.BigInteger(), nullable=True),
        sa.Column("transfer_speed", sa.Float(), nullable=True),
        sa.Column("speedup_ratio", sa.Float(), nullable=True),
        sa.Column("file_count", sa.Integer(), nullable=True),
        sa.Column("file_list", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("exit_code", sa.Integer(), nullable=True),
        sa.Column(
            "status", sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False
        ),
        sa.Column("is_dry_run", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_sync_logs_created_at", "sync_logs", ["created_at"], unique=False
    )
    op.create_index("ix_sync_logs_exit_code", "sync_logs", ["exit_code"], unique=False)
    op.create_index(
        op.f("ix_sync_logs_is_dry_run"), "sync_logs", ["is_dry_run"], unique=False
    )
    op.create_index(
        op.f("ix_sync_logs_source_name"), "sync_logs", ["source_name"], unique=False
    )
    op.create_index(
        "ix_sync_logs_source_name_created_at",
        "sync_logs",
        ["source_name", "created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_sync_logs_start_time"), "sync_logs", ["start_time"], unique=False
    )
    op.create_table(
        "sync_source_monitors",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "source_name", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False
        ),
        sa.Column("expected_interval_hours", sa.Integer(), nullable=False),
        sa.Column("grace_multiplier", sa.Float(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("last_sync_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_sync_source_monitors_source_name"),
        "sync_source_monitors",
        ["source_name"],
        unique=True,
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "username", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False
        ),
        sa.Column(
            "email", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False
        ),
        sa.Column(
            "password_hash",
            sqlmodel.sql.sqltypes.AutoString(length=255),
            nullable=False,
        ),
        sa.Column("role", sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "auth_provider", sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False
        ),
        sa.Column(
            "oidc_subject", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True
        ),
        sa.Column(
            "oidc_issuer", sqlmodel.sql.sqltypes.AutoString(length=512), nullable=True
        ),
        sa.Column("last_login_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("oidc_subject"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(op.f("ix_users_username"), "users", ["username"], unique=True)
    op.create_table(
        "webhook_endpoints",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
        sa.Column("url", sqlmodel.sql.sqltypes.AutoString(length=2048), nullable=False),
        sa.Column("headers", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "webhook_type", sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False
        ),
        sa.Column(
            "source_filters", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("consecutive_failures", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_webhook_endpoints_enabled"),
        "webhook_endpoints",
        ["enabled"],
        unique=False,
    )
    op.create_table(
        "api_keys",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "key_hash", sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False
        ),
        sa.Column(
            "key_prefix", sqlmodel.sql.sqltypes.AutoString(length=12), nullable=False
        ),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
        sa.Column(
            "source_names", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("last_used_at", sa.DateTime(), nullable=True),
        sa.Column("expires_at", sa.DateTime(), nullable=True),
        sa.Column("user_id", sa.Uuid(), nullable=True),
        sa.Column(
            "role_override", sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("key_hash"),
    )
    op.create_index(op.f("ix_api_keys_user_id"), "api_keys", ["user_id"], unique=False)
    op.create_table(
        "failure_events",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "source_name", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False
        ),
        sa.Column(
            "failure_type", sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False
        ),
        sa.Column("detected_at", sa.DateTime(), nullable=False),
        sa.Column("sync_log_id", sa.Uuid(), nullable=True),
        sa.Column("notified", sa.Boolean(), nullable=False),
        sa.Column("details", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["sync_log_id"],
            ["sync_logs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_failure_events_detected_at"),
        "failure_events",
        ["detected_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_failure_events_failure_type"),
        "failure_events",
        ["failure_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_failure_events_source_name"),
        "failure_events",
        ["source_name"],
        unique=False,
    )
    op.create_index(
        "ix_failure_events_source_name_detected_at",
        "failure_events",
        ["source_name", "detected_at"],
        unique=False,
    )
    op.create_table(
        "oidc_config",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "issuer_url", sqlmodel.sql.sqltypes.AutoString(length=512), nullable=False
        ),
        sa.Column(
            "client_id", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False
        ),
        sa.Column(
            "encrypted_client_secret",
            sqlmodel.sql.sqltypes.AutoString(),
            nullable=False,
        ),
        sa.Column(
            "provider_name",
            sqlmodel.sql.sqltypes.AutoString(length=100),
            nullable=False,
        ),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("hide_local_login", sa.Boolean(), nullable=False),
        sa.Column(
            "scopes", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False
        ),
        sa.Column("configured_by_id", sa.Uuid(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["configured_by_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_oidc_config_configured_by_id"),
        "oidc_config",
        ["configured_by_id"],
        unique=False,
    )
    op.create_table(
        "password_reset_tokens",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "token_hash", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False
        ),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.Column("used", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_password_reset_tokens_user_id"),
        "password_reset_tokens",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "refresh_tokens",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "token_hash", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False
        ),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.Column("revoked", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_refresh_tokens_user_id"), "refresh_tokens", ["user_id"], unique=False
    )
    op.create_table(
        "smtp_config",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("host", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column("port", sa.Integer(), nullable=False),
        sa.Column(
            "username", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True
        ),
        sa.Column(
            "encrypted_password", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column(
            "encryption", sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False
        ),
        sa.Column(
            "from_address", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False
        ),
        sa.Column(
            "from_name", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False
        ),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("configured_by_id", sa.Uuid(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["configured_by_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_smtp_config_configured_by_id"),
        "smtp_config",
        ["configured_by_id"],
        unique=False,
    )
    op.create_table(
        "webhook_options",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("webhook_endpoint_id", sa.Uuid(), nullable=False),
        sa.Column("options", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["webhook_endpoint_id"], ["webhook_endpoints.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_webhook_options_webhook_endpoint_id"),
        "webhook_options",
        ["webhook_endpoint_id"],
        unique=True,
    )
    op.create_table(
        "notification_logs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("failure_event_id", sa.Uuid(), nullable=False),
        sa.Column("webhook_endpoint_id", sa.Uuid(), nullable=False),
        sa.Column(
            "status", sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False
        ),
        sa.Column("http_status_code", sa.Integer(), nullable=True),
        sa.Column("error_message", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("attempt_number", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["failure_event_id"],
            ["failure_events.id"],
        ),
        sa.ForeignKeyConstraint(
            ["webhook_endpoint_id"],
            ["webhook_endpoints.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_notification_logs_created_at",
        "notification_logs",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_notification_logs_failure_event_id"),
        "notification_logs",
        ["failure_event_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_notification_logs_webhook_endpoint_id"),
        "notification_logs",
        ["webhook_endpoint_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_notification_logs_webhook_endpoint_id"), table_name="notification_logs"
    )
    op.drop_index(
        op.f("ix_notification_logs_failure_event_id"), table_name="notification_logs"
    )
    op.drop_index("ix_notification_logs_created_at", table_name="notification_logs")
    op.drop_table("notification_logs")
    op.drop_index(
        op.f("ix_webhook_options_webhook_endpoint_id"), table_name="webhook_options"
    )
    op.drop_table("webhook_options")
    op.drop_index(op.f("ix_smtp_config_configured_by_id"), table_name="smtp_config")
    op.drop_table("smtp_config")
    op.drop_index(op.f("ix_refresh_tokens_user_id"), table_name="refresh_tokens")
    op.drop_table("refresh_tokens")
    op.drop_index(
        op.f("ix_password_reset_tokens_user_id"), table_name="password_reset_tokens"
    )
    op.drop_table("password_reset_tokens")
    op.drop_index(op.f("ix_oidc_config_configured_by_id"), table_name="oidc_config")
    op.drop_table("oidc_config")
    op.drop_index(
        "ix_failure_events_source_name_detected_at", table_name="failure_events"
    )
    op.drop_index(op.f("ix_failure_events_source_name"), table_name="failure_events")
    op.drop_index(op.f("ix_failure_events_failure_type"), table_name="failure_events")
    op.drop_index(op.f("ix_failure_events_detected_at"), table_name="failure_events")
    op.drop_table("failure_events")
    op.drop_index(op.f("ix_api_keys_user_id"), table_name="api_keys")
    op.drop_table("api_keys")
    op.drop_index(op.f("ix_webhook_endpoints_enabled"), table_name="webhook_endpoints")
    op.drop_table("webhook_endpoints")
    op.drop_index(op.f("ix_users_username"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_index(
        op.f("ix_sync_source_monitors_source_name"), table_name="sync_source_monitors"
    )
    op.drop_table("sync_source_monitors")
    op.drop_index(op.f("ix_sync_logs_start_time"), table_name="sync_logs")
    op.drop_index("ix_sync_logs_source_name_created_at", table_name="sync_logs")
    op.drop_index(op.f("ix_sync_logs_source_name"), table_name="sync_logs")
    op.drop_index(op.f("ix_sync_logs_is_dry_run"), table_name="sync_logs")
    op.drop_index("ix_sync_logs_exit_code", table_name="sync_logs")
    op.drop_index("ix_sync_logs_created_at", table_name="sync_logs")
    op.drop_table("sync_logs")
    # ### end Alembic commands ###
